### EXPERIMENTANDO

In [1]:
%matplotlib inline                                   

In [1]:
import matplotlib.pyplot as plt
import numpy as np  
import cv2  
import dlib  
import os




#JAWLINE_POINTS = list(range(0, 17))  
RIGHT_EYEBROW_POINTS = list(range(17, 22))  
LEFT_EYEBROW_POINTS = list(range(22, 27))  
NOSE_POINTS = list(range(27, 36))  
NOSE_PERSONAL =  list(range(31, 36))  
RIGHT_EYE_POINTS = list(range(36, 42))  
LEFT_EYE_POINTS = list(range(42, 48))  
MOUTH_OUTLINE_POINTS = list(range(48, 61))  
MOUTH_INNER_POINTS = list(range(61, 68))  

#+RIGHT_EYEBROW_POINTS+LEFT_EYEBROW_POINTS+RIGHT_EYE_POINTS+LEFT_EYE_POINTS

### TOMAR FOTO Y GUARDAR

In [1]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    font = cv2.FONT_HERSHEY_SIMPLEX
    #cv2.putText(frame,'OpenCV',(100,100), font, 4,(255,255,255),2,cv2.LINE_AA)
    
   
    cv2.circle(frame, (200,100), 3, (0,255, 0), 3)
    cv2.circle(frame, (300,50), 3, (0,255, 0), 3)
    cv2.circle(frame, (400,100), 3, (0,255, 0), 3)
    cv2.circle(frame, (200,400), 3, (0,255, 0), 3)
    cv2.circle(frame, (300,450), 3, (0,255, 0), 3)
    cv2.circle(frame, (400,400), 3, (0,255, 0), 3)
    cv2.circle(frame, (150,300), 3, (0,255, 0), 3)
    cv2.circle(frame, (150,200), 3, (0,255, 0), 3)
    cv2.circle(frame, (450,200), 3, (0,255, 0), 3)
    cv2.circle(frame, (450,300), 3, (0,255, 0), 3)
    
    
    cv2.imshow('READ A WEB CAM',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('t'):              
        file = "prueba_3.png"
        cv2.imwrite(file, frame)
        print("Taking image...")
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [6]:
for FileName in Folders:
    pathToFolder = FilePath + FileName
    File = str(FileName)
    print(pathToFolder)
    

data/arturo.jpg
data/arturo_1.jpg
data/arturo_2.jpg
data/chan.jpg
data/cristi.jpeg
data/cristi_2.jpg
data/geme1.PNG
data/geme2.PNG
data/griz.jpg
data/jaky.jpg
data/james.jpg
data/jet.jpg
data/lewa.png
data/lewa_2.jpg
data/m1.jpg
data/m2.jpg
data/m3.jpg
data/Maluma.jpg
data/mbappe.jpg
data/mesi.jpg
data/messi.jpg
data/messi_2.jpg
data/messi_3.jpg
data/messi_x.jpg
data/ozil.jpg
data/prueba.png
data/prueba_1.png
data/prueba_2.png
data/putin.jpg
data/scar.jpg
data/silvester.jpg
data/smash.jpg
data/suarez.jpg
data/thiago.jpg
data/zlatan.jpg


In [9]:
indices = []


faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')  
   
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')  
   

FilePath = "data/" # ubicar la ruta de la carpeta de archivos
Folders = os.listdir(FilePath) # entrar mediante OS a la carpeta de archivos
LabelCount = 1

for FileName in Folders:     
    pathToFolder = FilePath + FileName
         # Read the image  
    image = cv2.imread('data/prueba_2.png') 
    #################################################


    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  

     # Detect faces in the image  
    faces = faceCascade.detectMultiScale(  
       gray,  
       scaleFactor=1.05,  
       minNeighbors=5,  
       minSize=(100, 100),  
       flags=cv2.CASCADE_SCALE_IMAGE  
     )  

    print("Found {0} faces!".format(len(faces)))  
    conhola = 0
     # Draw a rectangle around the faces  
    for (x, y, w, h) in faces:  
        cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)  

       # Converting the OpenCV rectangle coordinates to Dlib rectangle  
        dlib_rect = dlib.rectangle(int(x), int(y), int(x + w), int(y + h))  

        landmarks = np.matrix([[p.x, p.y]  
                   for p in predictor(image, dlib_rect).parts()])


        landmarks_display = landmarks[RIGHT_EYEBROW_POINTS+LEFT_EYEBROW_POINTS+NOSE_POINTS+RIGHT_EYE_POINTS+LEFT_EYE_POINTS+MOUTH_OUTLINE_POINTS+MOUTH_INNER_POINTS]  
        #print(landmarks_display)

        cejaderecha_cara1 = landmarks[RIGHT_EYEBROW_POINTS]  
        ojoderecho_cara1 = landmarks[RIGHT_EYE_POINTS] 
        cejaizquierda_cara1 = landmarks[LEFT_EYEBROW_POINTS]  
        ojoizquierdo_cara1 = landmarks[LEFT_EYE_POINTS] 
        nariz_cara1 = landmarks[NOSE_POINTS]

        for idx, point in enumerate(landmarks_display):  

            pos = (point[0, 0], point[0, 1])  
            cv2.putText(image, str(idx), pos,  
               fontFace=cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,  
               fontScale=0.4,  
               color=(0, 0, 255))  

            conhola = conhola +1
            #print(conhola)

        cv2.circle(image, pos, 2, color=(0, 255, 255), thickness=-1)    

    #cv2.imshow("Landmarks found", image)     
    
   
    #######################################################################33    
    
    image_2 = cv2.imread(pathToFolder) ##########################################

    gray_2 = cv2.cvtColor(image_2, cv2.COLOR_BGR2GRAY)  

     # Detect faces in the image  
    faces_2 = faceCascade.detectMultiScale(  
       gray_2,  
       scaleFactor=1.05,  
       minNeighbors=5,  
       minSize=(100, 100),  
       flags=cv2.CASCADE_SCALE_IMAGE  
     )  

    print("Found {0} faces!".format(len(faces_2)))  
    conhola = 0
     # Draw a rectangle around the faces  
    for (x_2, y_2, w_2, h_2) in faces_2:  
        cv2.rectangle(image_2, (x_2, y_2), (x_2 + w_2, y_2 + h_2), (0, 255, 0), 2)  

       # Converting the OpenCV rectangle coordinates to Dlib rectangle  
        dlib_rect_2 = dlib.rectangle(int(x_2), int(y_2), int(x_2 + w_2), int(y_2 + h_2))  

        landmarks_2 = np.matrix([[p_2.x, p_2.y]  
                   for p_2 in predictor(image_2, dlib_rect_2).parts()])
        #print(landmarks_2)

        landmarks_display_2 = landmarks_2[RIGHT_EYEBROW_POINTS+LEFT_EYEBROW_POINTS+NOSE_POINTS+RIGHT_EYE_POINTS+LEFT_EYE_POINTS+MOUTH_OUTLINE_POINTS+MOUTH_INNER_POINTS]  
        #print(landmarks_display_2)
        cejaderecha_cara2 = landmarks_2[RIGHT_EYEBROW_POINTS]  
        ojoderecho_cara2 = landmarks_2[RIGHT_EYE_POINTS] 
        cejaizquierda_cara2 = landmarks_2[LEFT_EYEBROW_POINTS]  
        ojoizquierdo_cara2 = landmarks_2[LEFT_EYE_POINTS] 
        nariz_cara2 = landmarks_2[NOSE_POINTS]

        for idx_2, point_2 in enumerate(landmarks_display_2):  

            pos_2 = (point_2[0, 0], point_2[0, 1])  
            cv2.putText(image_2, str(idx_2), pos_2,  
               fontFace=cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,  
               fontScale=0.4,  
               color=(0, 0, 255))  

            conhola = conhola +1
            #print(conhola)

        cv2.circle(image_2, pos_2, 2, color=(0, 255, 255), thickness=-1)    

    #landmarks
    
#cv2.imshow("Landmarks image_2", image_2)  
#cv2.waitKey(0)
#cv2.destroyAllWindows()


##############################################################################################################
#####DISTANCIAS EUCLIDEAS DE OJOS Y CEJAS CARA 1
###############################################################################################################

        #CARA 1
        #ojo derecho
        ojoderecho_cara1 = ojoderecho_cara1[0:5]
        #ojo izquierdo

        ojoizquierdo_cara1 = ojoizquierdo_cara1[0:5]

        #print(ojoderecho_cara1)
        #print(cejaderecha_cara1)
        #print(ojoizquierdo_cara1)
        #print(cejaizquierda_cara1)
        #Coordenadas x e y de los ojos contra las cejas del ojo derecho de la cara1
        x1 = cejaderecha_cara1[:,0]
        y1 = cejaderecha_cara1[:,1]

        x2 = ojoderecho_cara1[:,0]
        y2 = ojoderecho_cara1[:,1]

        x3 =cejaizquierda_cara1[:,0]
        y3 = cejaizquierda_cara1[:,1]

        x4 = ojoizquierdo_cara1[:,0]
        y4 = ojoizquierdo_cara1[:,1]

        x5 = nariz_cara1[:,0]
        y5 = nariz_cara1[:,1]

        vectorDistanciasDer_cara1 = []
        vectorDistanciasIzq_cara1 = []


        euclides_derecho_cara1 = ((np.array(x1-x2))**2+(np.array(y1-y2))**2)**(1/2)  
        euclides_izquierdo_cara1 = ((np.array(x3-x4))**2+(np.array(y3-y4))**2)**(1/2)


        print("############################################")   

        print(euclides_derecho_cara1)
        print(euclides_izquierdo_cara1)

        print("############################################") 

        norm_derecho_cara1 = (euclides_derecho_cara1-min(euclides_derecho_cara1))/(max(euclides_derecho_cara1)-min(euclides_derecho_cara1))
        print(norm_derecho_cara1)    

        norm_izquierda_cara1 = (euclides_izquierdo_cara1-min(euclides_izquierdo_cara1))/(max(euclides_izquierdo_cara1)-min(euclides_izquierdo_cara1))
        print(norm_izquierda_cara1)

        print("############################################") 
        norm_nariz_cara1_x = (np.array(x5)-min(np.array(x5)))/(max(np.array(x5)-min(np.array(x5))))
        print(norm_nariz_cara1_x)
        print("############################################") 
        norm_nariz_cara1_y = (np.array(y5)-min(np.array(y5)))/(max(np.array(y5)-min(np.array(y5))))
        print(norm_nariz_cara1_y)

        #hallando los centroides
        cx = np.mean(norm_nariz_cara1_x)
        cy = np.mean(norm_nariz_cara1_y)

        print(cx,cy)


        ########################################################################################################
        ##### DISTANCIAS EUCLIDEAS DE OJOS Y CEJAS CARA 2
        ########################################################################################################

        #CARA 2
        #ojo derecho
        ojoderecho_cara2 = ojoderecho_cara2[0:5]
        #ojo izquierdo

        ojoizquierdo_cara2 = ojoizquierdo_cara2[0:5]

        #print(ojoderecho_cara1)
        #print(cejaderecha_cara1)
        #print(ojoizquierdo_cara1)
        #print(cejaizquierda_cara1)
        #Coordenadas x e y de los ojos contra las cejas del ojo derecho de la cara1
        ix1 = cejaderecha_cara2[:,0]
        iy1 = cejaderecha_cara2[:,1]

        ix2 = ojoderecho_cara2[:,0]
        iy2 = ojoderecho_cara2[:,1]

        ix3 =cejaizquierda_cara2[:,0]
        iy3 = cejaizquierda_cara2[:,1]

        ix4 = ojoizquierdo_cara2[:,0]
        iy4 = ojoizquierdo_cara2[:,1]

        ix5 = nariz_cara2[:,0]
        iy5 = nariz_cara2[:,1]

        vectorDistanciasDer_cara2 = []
        vectorDistanciasIzq_cara2 = []


        euclides_derecho_cara2 = ((np.array(ix1-ix2))**2+(np.array(iy1-iy2))**2)**(1/2)  
        euclides_izquierdo_cara2 = ((np.array(ix3-ix4))**2+(np.array(iy3-iy4))**2)**(1/2)


        print("############################################")   

        print(euclides_derecho_cara2)
        print(euclides_izquierdo_cara2)

        print("############################################") 

        norm_derecho_cara2 = (euclides_derecho_cara2-min(euclides_derecho_cara2))/(max(euclides_derecho_cara2)-min(euclides_derecho_cara2))
        print(norm_derecho_cara2)    

        norm_izquierda_cara2 = (euclides_izquierdo_cara2-min(euclides_izquierdo_cara2))/(max(euclides_izquierdo_cara2)-min(euclides_izquierdo_cara2))
        print(norm_izquierda_cara2)

        print("############################################") 
        norm_nariz_cara2_ix = (np.array(ix5)-min(np.array(ix5)))/(max(np.array(ix5)-min(np.array(ix5))))
        print(norm_nariz_cara2_ix)
        print("############################################") 
        norm_nariz_cara2_iy = (np.array(iy5)-min(np.array(iy5)))/(max(np.array(iy5)-min(np.array(iy5))))
        print(norm_nariz_cara2_iy)

        #hallando los centroides
        cxi = np.mean(norm_nariz_cara2_ix)
        cyi = np.mean(norm_nariz_cara2_iy)

        print(cxi,cyi)


        ###########################################################################################################
        #######EUCLIDEANO PARA DOS ROSTROS
        ############################################################################################################

        norm_derecho_cara1   
        norm_izquierda_cara1

        norm_derecho_cara2  
        norm_izquierda_cara2

        dist_derechos = ((norm_derecho_cara1[0]-norm_derecho_cara2[0])**2+
                                (norm_derecho_cara1[1]-norm_derecho_cara2[1])**2+
                                (norm_derecho_cara1[2]-norm_derecho_cara2[2])**2+
                                (norm_derecho_cara1[3]-norm_derecho_cara2[3])**2+
                                (norm_derecho_cara1[4]-norm_derecho_cara2[4])**2)**(1/2)

        dist_izquierdos = ((norm_izquierda_cara1[0]-norm_izquierda_cara2[0])**2+
                           (norm_izquierda_cara1[1]-norm_izquierda_cara2[1])**2+
                           (norm_izquierda_cara1[2]-norm_izquierda_cara2[2])**2+
                           (norm_izquierda_cara1[3]-norm_izquierda_cara2[3])**2+
                           (norm_izquierda_cara1[4]-norm_izquierda_cara2[4])**2)**(1/2)   

        dist_nariz = ((cx-cxi)**2+(cy-cyi)**2)**(1/2)


        print(dist_derechos)
        print(dist_izquierdos)
        print(dist_nariz)

        ###################################################################################################
        ##### RESULTADO FINAL
        ###################################################################################################
        resultado = (((dist_derechos+dist_izquierdos+dist_nariz)/3)*100)
        print(((dist_derechos+dist_izquierdos+dist_nariz)/3)*100)
        print("???????????????????????????????")
        
        indices.append(resultado)
print(indices)        

Found 1 faces!
Found 1 faces!
############################################
[[ 33.01514804]
 [ 38.58756276]
 [ 40.24922359]
 [ 47.12748667]
 [ 42.95346319]]
[[ 34.92849839]
 [ 37.12142239]
 [ 39.05124838]
 [ 41.        ]
 [ 50.93132631]]
############################################
[[ 0.        ]
 [ 0.39486118]
 [ 0.51260643]
 [ 1.        ]
 [ 0.70422879]]
[[ 0.        ]
 [ 0.13703353]
 [ 0.25762634]
 [ 0.37940179]
 [ 1.        ]]
############################################
[[ 0.44]
 [ 0.44]
 [ 0.44]
 [ 0.42]
 [ 0.  ]
 [ 0.2 ]
 [ 0.46]
 [ 0.74]
 [ 1.  ]]
############################################
[[ 0.        ]
 [ 0.26190476]
 [ 0.53571429]
 [ 0.80952381]
 [ 0.88095238]
 [ 0.94047619]
 [ 1.        ]
 [ 0.95238095]
 [ 0.89285714]]
0.46 0.69708994709
############################################
[[ 26.2488095 ]
 [ 31.2409987 ]
 [ 32.24903099]
 [ 36.34556369]
 [ 46.09772229]]
[[ 37.16180835]
 [ 31.25699922]
 [ 29.61418579]
 [ 29.15475947]
 [ 39.81205847]]
################################

Found 1 faces!
Found 0 faces!
Found 1 faces!
Found 1 faces!
############################################
[[ 33.01514804]
 [ 38.58756276]
 [ 40.24922359]
 [ 47.12748667]
 [ 42.95346319]]
[[ 34.92849839]
 [ 37.12142239]
 [ 39.05124838]
 [ 41.        ]
 [ 50.93132631]]
############################################
[[ 0.        ]
 [ 0.39486118]
 [ 0.51260643]
 [ 1.        ]
 [ 0.70422879]]
[[ 0.        ]
 [ 0.13703353]
 [ 0.25762634]
 [ 0.37940179]
 [ 1.        ]]
############################################
[[ 0.44]
 [ 0.44]
 [ 0.44]
 [ 0.42]
 [ 0.  ]
 [ 0.2 ]
 [ 0.46]
 [ 0.74]
 [ 1.  ]]
############################################
[[ 0.        ]
 [ 0.26190476]
 [ 0.53571429]
 [ 0.80952381]
 [ 0.88095238]
 [ 0.94047619]
 [ 1.        ]
 [ 0.95238095]
 [ 0.89285714]]
0.46 0.69708994709
############################################
[[ 10.29563014]
 [ 12.04159458]
 [ 13.03840481]
 [ 14.31782106]
 [ 16.64331698]]
[[ 14.76482306]
 [ 10.19803903]
 [ 11.04536102]
 [ 12.36931688]
 [ 15.8113883 ]]
##

Found 1 faces!
############################################
[[ 33.01514804]
 [ 38.58756276]
 [ 40.24922359]
 [ 47.12748667]
 [ 42.95346319]]
[[ 34.92849839]
 [ 37.12142239]
 [ 39.05124838]
 [ 41.        ]
 [ 50.93132631]]
############################################
[[ 0.        ]
 [ 0.39486118]
 [ 0.51260643]
 [ 1.        ]
 [ 0.70422879]]
[[ 0.        ]
 [ 0.13703353]
 [ 0.25762634]
 [ 0.37940179]
 [ 1.        ]]
############################################
[[ 0.44]
 [ 0.44]
 [ 0.44]
 [ 0.42]
 [ 0.  ]
 [ 0.2 ]
 [ 0.46]
 [ 0.74]
 [ 1.  ]]
############################################
[[ 0.        ]
 [ 0.26190476]
 [ 0.53571429]
 [ 0.80952381]
 [ 0.88095238]
 [ 0.94047619]
 [ 1.        ]
 [ 0.95238095]
 [ 0.89285714]]
0.46 0.69708994709
############################################
[[ 18.43908891]
 [ 22.82542442]
 [ 24.69817807]
 [ 26.68332813]
 [ 26.2488095 ]]
[[ 25.23885893]
 [ 18.97366596]
 [ 20.09975124]
 [ 22.84731932]
 [ 33.24154028]]
############################################
[[

Found 1 faces!
############################################
[[ 33.01514804]
 [ 38.58756276]
 [ 40.24922359]
 [ 47.12748667]
 [ 42.95346319]]
[[ 34.92849839]
 [ 37.12142239]
 [ 39.05124838]
 [ 41.        ]
 [ 50.93132631]]
############################################
[[ 0.        ]
 [ 0.39486118]
 [ 0.51260643]
 [ 1.        ]
 [ 0.70422879]]
[[ 0.        ]
 [ 0.13703353]
 [ 0.25762634]
 [ 0.37940179]
 [ 1.        ]]
############################################
[[ 0.44]
 [ 0.44]
 [ 0.44]
 [ 0.42]
 [ 0.  ]
 [ 0.2 ]
 [ 0.46]
 [ 0.74]
 [ 1.  ]]
############################################
[[ 0.        ]
 [ 0.26190476]
 [ 0.53571429]
 [ 0.80952381]
 [ 0.88095238]
 [ 0.94047619]
 [ 1.        ]
 [ 0.95238095]
 [ 0.89285714]]
0.46 0.69708994709
############################################
[[ 26.62705391]
 [ 28.28427125]
 [ 30.88689042]
 [ 34.71310992]
 [ 37.64306045]]
[[ 29.27456234]
 [ 23.34523506]
 [ 24.69817807]
 [ 27.45906044]
 [ 34.17601498]]
############################################
[[

Found 1 faces!
############################################
[[ 33.01514804]
 [ 38.58756276]
 [ 40.24922359]
 [ 47.12748667]
 [ 42.95346319]]
[[ 34.92849839]
 [ 37.12142239]
 [ 39.05124838]
 [ 41.        ]
 [ 50.93132631]]
############################################
[[ 0.        ]
 [ 0.39486118]
 [ 0.51260643]
 [ 1.        ]
 [ 0.70422879]]
[[ 0.        ]
 [ 0.13703353]
 [ 0.25762634]
 [ 0.37940179]
 [ 1.        ]]
############################################
[[ 0.44]
 [ 0.44]
 [ 0.44]
 [ 0.42]
 [ 0.  ]
 [ 0.2 ]
 [ 0.46]
 [ 0.74]
 [ 1.  ]]
############################################
[[ 0.        ]
 [ 0.26190476]
 [ 0.53571429]
 [ 0.80952381]
 [ 0.88095238]
 [ 0.94047619]
 [ 1.        ]
 [ 0.95238095]
 [ 0.89285714]]
0.46 0.69708994709
############################################
[[ 38.89730068]
 [ 39.20459157]
 [ 39.81205847]
 [ 44.40720662]
 [ 51.73973328]]
[[ 41.14608122]
 [ 35.6931366 ]
 [ 41.        ]
 [ 46.32493929]
 [ 58.05170109]]
############################################
[[